// subtitle languages

const langs = {
    languages: {
      alb: 'Albanian',
      ara: 'Arabic',
      baq: 'Basque',
      pob: 'Brazilian',
      bul: 'Bulgarian',
      cat: 'Catalan',
      chi: 'Chinese (simplified)',
      zht: 'Chinese (traditional)',
      hrv: 'Croatian',
      cze: 'Czech',
      dan: 'Danish',
      dut: 'Dutch',
      eng: 'English',
      est: 'Estonian',
      fin: 'Finnish',
      fre: 'French',
      glg: 'Galician',
      geo: 'Georgian',
      ger: 'German',
      ell: 'Greek',
      heb: 'Hebrew',
      hin: 'Hindi',
      hun: 'Hungarian',
      ice: 'Icelandic',
      ind: 'Indonesian',
      ita: 'Italian',
      jpn: 'Japanese',
      khm: 'Khmer',
      kor: 'Korean',
      mac: 'Macedonian',
      may: 'Malay',
      nor: 'Norwegian',
      per: 'Persian',
      pol: 'Polish',
      por: 'Portuguese',
      rum: 'Romanian',
      rus: 'Russian',
      scc: 'Serbian',
      sin: 'Sinhalese',
      slo: 'Slovak',
      slv: 'Slovenian',
      spa: 'Spanish',
      swe: 'Swedish',
      tgl: 'Tagalog',
      tha: 'Thai',
      tur: 'Turkish',
      ukr: 'Ukrainian',
      vie: 'Vietnamese'
    }
}

export default langs
